### PR TITLE
chore: setup express

### PR DESCRIPTION
**Pull request by sojida**

### CODE REVIEW

**Comment by sojida** [comment]
> @sojida noticed you dint configure db e.t.c

@9trocode Yea. The scope of the task was to set up express. We have not discussed our DB and ORM of choice. What would you like us to use? So I can add it to this or to a separate PR depending on what you guys want

cc @vic3king @otseobande @9trocode

**Comment by vic3king** [comment]
> > @sojida noticed you dint configure db e.t.c
> 
> @9trocode Yea. The scope of the task was to set up express. We have not discussed our DB and ORM of choice. What would you like us to use? So I can add it to this or to a separate PR depending on what you guys want
> 
> cc @vic3king @otseobande @9trocode

I think Postgres/Sequelize should do.

**Comment by 9trocode** [comment]
> > @sojida noticed you dint configure db e.t.c
> 
> @9trocode Yea. The scope of the task was to set up express. We have not discussed our DB and ORM of choice. What would you like us to use? So I can add it to this or to a separate PR depending on what you guys want
> 
> cc @vic3king @otseobande @9trocode

Okay well noted

**Comment by 9trocode** [comment]
> > > @sojida noticed you dint configure db e.t.c
> > 
> > 
> > @9trocode Yea. The scope of the task was to set up express. We have not discussed our DB and ORM of choice. What would you like us to use? So I can add it to this or to a separate PR depending on what you guys want
> > cc @vic3king @otseobande @9trocode
> 
> I think Postgres/Sequelize should do.

Yea let's go ahead with this

**Pull request merged**
